-- =====================================================================
-- V10: Module De thi (exams) + cac quan he N:N
-- =====================================================================

-- 1) Bang de thi
CREATE TABLE exams (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(20)  NOT NULL UNIQUE,
    name             VARCHAR(255) NOT NULL,
    subject_id       BIGINT       NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    type             VARCHAR(20)  NOT NULL,
    duration_minutes INT,
    publish_at       TIMESTAMPTZ,
    end_at           TIMESTAMPTZ,
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100)
);
CREATE INDEX idx_exams_subject_id ON exams (subject_id);
CREATE INDEX idx_exams_status     ON exams (status);
CREATE INDEX idx_exams_type       ON exams (type);
CREATE INDEX idx_exams_created_at ON exams (created_at);

-- 2) De <-> Bai tap (join + diem + thu tu)
CREATE TABLE exam_exercises (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id     BIGINT NOT NULL REFERENCES exams (id)     ON DELETE CASCADE,
    exercise_id BIGINT NOT NULL REFERENCES exercises (id) ON DELETE RESTRICT,
    sort_order  INT    NOT NULL DEFAULT 0,
    points      NUMERIC(6,2),
    CONSTRAINT uq_exam_exercise UNIQUE (exam_id, exercise_id)
);
CREATE INDEX idx_exam_exercises_exam ON exam_exercises (exam_id);

-- 3) Diem tung y cho bai Dung/Sai
CREATE TABLE exam_tf_item_scores (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_exercise_id BIGINT NOT NULL REFERENCES exam_exercises (id)   ON DELETE CASCADE,
    tf_item_id       BIGINT NOT NULL REFERENCES true_false_items (id) ON DELETE CASCADE,
    points           NUMERIC(6,2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_exam_tf_item UNIQUE (exam_exercise_id, tf_item_id)
);

-- 4) De <-> Lop
CREATE TABLE exam_classes (
    exam_id  BIGINT NOT NULL REFERENCES exams (id)   ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES classes (id) ON DELETE RESTRICT,
    PRIMARY KEY (exam_id, class_id)
);

-- 5) De <-> Hoc sinh (chi dung cho SUPPLEMENTARY)
CREATE TABLE exam_students (
    exam_id BIGINT NOT NULL REFERENCES exams (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (exam_id, user_id)
);

-- 6) Quyen module Exam
INSERT INTO permissions (code, resource, action, description) VALUES
    ('EXAM:READ',   'EXAM', 'READ',   'Xem de thi'),
    ('EXAM:WRITE',  'EXAM', 'WRITE',  'Tao / sua de thi'),
    ('EXAM:DELETE', 'EXAM', 'DELETE', 'Xoa de thi');

-- ADMIN: toan bo
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN' AND p.resource = 'EXAM';

-- TEACHER: doc + tao/sua
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'TEACHER' AND p.resource = 'EXAM' AND p.action IN ('READ', 'WRITE');

-- EMPLOYEE: chi xem
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE' AND p.resource = 'EXAM' AND p.action = 'READ';
