-- =====================================================================
-- V13: Trang thai De thi <-> Hoc vien (1 ban ghi / 1 cot status)
-- materialize cho ca BY_CLASS (thanh vien khoa) lan SUPPLEMENTARY (HS duoc chon)
-- status: CHUA_PHAT_HANH | DA_PHAT_HANH | DANG_KIEM_TRA | DA_LAM | DA_XOA
-- (QUA_HAN tinh luc doc theo end_at, khong luu cung)
-- =====================================================================

CREATE TABLE exam_student (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id      BIGINT       NOT NULL REFERENCES exams (id) ON DELETE CASCADE,
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    source       VARCHAR(20)  NOT NULL,                       -- CLASS | SUPPLEMENTARY
    status       VARCHAR(20)  NOT NULL DEFAULT 'CHUA_PHAT_HANH',
    started_at   TIMESTAMPTZ,
    submitted_at TIMESTAMPTZ,
    score        NUMERIC(6,2),
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT uq_exam_student UNIQUE (exam_id, user_id)
);

CREATE INDEX idx_exam_student_user   ON exam_student (user_id);
CREATE INDEX idx_exam_student_exam   ON exam_student (exam_id);
CREATE INDEX idx_exam_student_status ON exam_student (status);
