-- =====================================================================
-- V14: Danh muc Chuyen de (topics) — phu thuoc Mon hoc (1 mon : N chuyen de)
-- Them tu DB (chua co giao dien CRUD), chi dung lam dropdown.
-- Gom: ten + so thu tu (sort_order).
-- =====================================================================

CREATE TABLE topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id  BIGINT       NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    name        VARCHAR(255) NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0
);

CREATE INDEX idx_topics_subject ON topics (subject_id);

-- -------------------------------------------------------------------
-- Quyen: chi READ (danh muc co dinh), gan cho TAT CA role de lam dropdown
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('TOPIC:READ', 'TOPIC', 'READ', 'Xem chuyen de');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE p.code = 'TOPIC:READ';
