-- =====================================================================
-- V1: Khoi tao schema Auth + RBAC
-- =====================================================================

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(30)  NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL UNIQUE,
    resource    VARCHAR(50)  NOT NULL,
    action      VARCHAR(50)  NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    email         VARCHAR(150) UNIQUE,
    phone         VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(150),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_token_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_user ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------
-- Seed: cac vai tro co dinh
-- ---------------------------------------------------------------------
INSERT INTO roles (name, description) VALUES
    ('ADMIN',     'Quan tri he thong'),
    ('EMPLOYEE',  'Nhan vien (le tan, ke toan, tu van)'),
    ('TEACHER',   'Giao vien'),
    ('ASSISTANT', 'Tro giang'),
    ('STUDENT',   'Hoc vien'),
    ('PARENT',    'Phu huynh');

-- ---------------------------------------------------------------------
-- Seed: quyen chi tiet cho module Auth/RBAC (cac module khac bo sung sau)
-- ---------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('USER:READ',   'USER', 'READ',   'Xem nguoi dung'),
    ('USER:WRITE',  'USER', 'WRITE',  'Tao / sua nguoi dung'),
    ('USER:DELETE', 'USER', 'DELETE', 'Xoa nguoi dung'),
    ('ROLE:READ',   'ROLE', 'READ',   'Xem vai tro / quyen'),
    ('ROLE:WRITE',  'ROLE', 'WRITE',  'Gan vai tro / quyen');

-- ADMIN nhan toan bo quyen hien co
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ADMIN';
