-- =====================================================================
-- V20: Co so (branches) + Phong hoc (rooms) + Ngay nghi (holidays)
-- =====================================================================
CREATE TABLE branches (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL UNIQUE,
    name       VARCHAR(150) NOT NULL,
    address    VARCHAR(255),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE TABLE rooms (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL UNIQUE,
    name       VARCHAR(150) NOT NULL,
    branch_id  BIGINT       NOT NULL REFERENCES branches (id) ON DELETE RESTRICT,
    capacity   INT,
    note       VARCHAR(255),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
CREATE INDEX idx_rooms_branch ON rooms (branch_id);

CREATE TABLE holidays (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE         NOT NULL,
    name         VARCHAR(150) NOT NULL,
    branch_id    BIGINT REFERENCES branches (id) ON DELETE CASCADE,  -- NULL = toan he thong
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT uq_holiday UNIQUE (holiday_date, branch_id)
);
CREATE INDEX idx_holidays_date ON holidays (holiday_date);

-- -------------------------------------------------------------------
-- Quyen ROOM:READ / ROOM:WRITE
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('ROOM:READ',  'ROOM', 'READ',  'Xem co so / phong hoc'),
    ('ROOM:WRITE', 'ROOM', 'WRITE', 'Tao / sua co so / phong hoc');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN' AND p.resource = 'ROOM';

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name IN ('EMPLOYEE', 'TEACHER') AND p.resource = 'ROOM' AND p.action = 'READ';
