-- =====================================================================
-- V21: Bang lien ket Hoc vien (STUDENT) <-> Phu huynh (PARENT) - N:N tren users
-- Dung quyen USER:READ / USER:WRITE (mot phan quan ly nguoi dung).
-- =====================================================================
CREATE TABLE student_parents (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    parent_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    relationship VARCHAR(30),
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT uq_student_parent UNIQUE (student_id, parent_id)
);
CREATE INDEX idx_student_parents_student ON student_parents (student_id);
CREATE INDEX idx_student_parents_parent  ON student_parents (parent_id);
