-- =====================================================================
-- V22: Quy tac lap lich (class_schedules) + Buoi hoc cu the (class_sessions)
--      + ALTER class_students ADD enrolled_at (ngay ghi danh)
-- Khong them permission moi: dung CLASS:READ / CLASS:WRITE
-- =====================================================================

-- Quy tac lap
CREATE TABLE class_schedules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id         BIGINT      NOT NULL REFERENCES classes (id) ON DELETE CASCADE,
    recurrence_type  VARCHAR(10) NOT NULL,                 -- ONCE | DAILY | WEEKLY
    day_of_week      SMALLINT,                             -- ISO 1..7 (chi WEEKLY; 1=Thu Hai ... 7=Chu Nhat)
    start_date       DATE        NOT NULL,
    end_date         DATE        NOT NULL,                 -- ONCE: = start_date
    start_time       TIME        NOT NULL,
    duration_minutes INT         NOT NULL,
    room_id          BIGINT REFERENCES rooms (id) ON DELETE SET NULL,
    teacher_id       BIGINT REFERENCES users (id) ON DELETE SET NULL,
    active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
CREATE INDEX idx_class_schedules_class ON class_schedules (class_id);

-- Buoi hoc cu the
CREATE TABLE class_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id         BIGINT      NOT NULL REFERENCES classes (id) ON DELETE CASCADE,
    schedule_id      BIGINT REFERENCES class_schedules (id) ON DELETE SET NULL,
    session_date     DATE        NOT NULL,
    start_time       TIME        NOT NULL,
    duration_minutes INT         NOT NULL,
    room_id          BIGINT REFERENCES rooms (id) ON DELETE SET NULL,
    teacher_id       BIGINT REFERENCES users (id) ON DELETE SET NULL,
    status           VARCHAR(12) NOT NULL DEFAULT 'PLANNED', -- PLANNED|CANCELLED|DONE
    cancel_reason    VARCHAR(255),
    is_manual        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_class_session UNIQUE (class_id, session_date, start_time)
);
CREATE INDEX idx_class_sessions_date    ON class_sessions (session_date);
CREATE INDEX idx_class_sessions_room    ON class_sessions (room_id, session_date);
CREATE INDEX idx_class_sessions_teacher ON class_sessions (teacher_id, session_date);

-- Ngay ghi danh (de loc lich HV tu luc vao lop)
ALTER TABLE class_students ADD COLUMN enrolled_at DATE;
