-- =====================================================================
-- V23: Diem danh tung buoi (session_attendance)
-- =====================================================================
CREATE TABLE session_attendance (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL REFERENCES class_sessions (id) ON DELETE CASCADE,
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(15) NOT NULL DEFAULT 'CHUA_CHECKIN', -- CHUA_CHECKIN|CO_MAT|TRE|VANG|CO_PHEP
    check_in_at  TIMESTAMPTZ,
    check_out_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_session_attendance UNIQUE (session_id, user_id)
);
CREATE INDEX idx_session_attendance_session ON session_attendance (session_id);
CREATE INDEX idx_session_attendance_user    ON session_attendance (user_id);
