-- =====================================================================
-- V24: Don xin nghi phep (leave_requests)
-- Quyen LEAVE:READ / LEAVE:WRITE / LEAVE:APPROVE
--   ADMIN          : tat ca (READ + WRITE + APPROVE)
--   TEACHER        : READ + APPROVE
--   STUDENT, PARENT: READ + WRITE
-- =====================================================================
CREATE TABLE leave_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    requested_by BIGINT      NOT NULL REFERENCES users (id),
    scope        VARCHAR(10) NOT NULL,                              -- SESSION | RANGE
    session_id   BIGINT REFERENCES class_sessions (id) ON DELETE CASCADE,
    class_id     BIGINT REFERENCES classes (id) ON DELETE CASCADE,  -- null = tat ca lop
    date_from    DATE,
    date_to      DATE,
    reason       TEXT,
    status       VARCHAR(10) NOT NULL DEFAULT 'PENDING',            -- PENDING|APPROVED|REJECTED
    reviewed_by  BIGINT REFERENCES users (id),
    reviewed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100)
);
CREATE INDEX idx_leave_student ON leave_requests (student_id);
CREATE INDEX idx_leave_status  ON leave_requests (status);

-- -------------------------------------------------------------------
-- Quyen LEAVE:READ / LEAVE:WRITE / LEAVE:APPROVE
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('LEAVE:READ',    'LEAVE', 'READ',    'Xem don nghi'),
    ('LEAVE:WRITE',   'LEAVE', 'WRITE',   'Tao don nghi'),
    ('LEAVE:APPROVE', 'LEAVE', 'APPROVE', 'Duyet don nghi');

-- ADMIN: tat ca quyen LEAVE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN' AND p.resource = 'LEAVE';

-- TEACHER: READ + APPROVE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'TEACHER' AND p.resource = 'LEAVE' AND p.action IN ('READ', 'APPROVE');

-- STUDENT + PARENT: READ + WRITE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name IN ('STUDENT', 'PARENT') AND p.resource = 'LEAVE' AND p.action IN ('READ', 'WRITE');
