-- =====================================================================
-- V25: Module THONG BAO (notification) - Outbox + Push (§5 SPEC_LichHoc_CHITIET)
-- device_tokens: token thiet bi de gui push
-- notifications: hop thu di (outbox), payload luu JSON dang chuoi (TEXT)
-- notification_preferences: opt-in + gio im lang theo tung loai
-- =====================================================================
CREATE TABLE device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token      VARCHAR(255) NOT NULL,
    platform   VARCHAR(10)  NOT NULL,                    -- IOS | ANDROID
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_device_token UNIQUE (token)
);
CREATE INDEX idx_device_tokens_user ON device_tokens (user_id);

CREATE TABLE notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    channel           VARCHAR(10)  NOT NULL DEFAULT 'PUSH',
    type              VARCHAR(30)  NOT NULL,
    title             VARCHAR(200),
    body              VARCHAR(500),
    payload           TEXT,                              -- JSON dang chuoi (tranh bay JSONB <-> ddl validate)
    status            VARCHAR(10)  NOT NULL DEFAULT 'PENDING', -- PENDING | SENT | FAILED
    dedupe_key        VARCHAR(150) UNIQUE,
    retry_count       INT          NOT NULL DEFAULT 0,
    sent_at           TIMESTAMPTZ,
    error             VARCHAR(500),
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100)
);
CREATE INDEX idx_notifications_status ON notifications (status);

CREATE TABLE notification_preferences (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(30)  NOT NULL,
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    quiet_from TIME,
    quiet_to   TIME,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_notif_pref UNIQUE (user_id, type)
);
CREATE INDEX idx_notif_pref_user ON notification_preferences (user_id);
