-- =====================================================================
-- V27: Cham cong giao vien bang QR phong
-- 1) rooms.qr_code: ma QR tinh cua phong (in dan tai phong hoc)
-- 2) session_teacher_attendance: cong day cua GV theo tung buoi
--    status: DUNG_GIO | VAO_TRE | VANG
-- =====================================================================

ALTER TABLE rooms ADD COLUMN qr_code VARCHAR(36);
UPDATE rooms SET qr_code = gen_random_uuid()::text WHERE qr_code IS NULL;
ALTER TABLE rooms ALTER COLUMN qr_code SET NOT NULL;
-- gen_random_uuid() co san tren PostgreSQL 13+ (pgcrypto built-in)

CREATE TABLE session_teacher_attendance (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT      NOT NULL REFERENCES class_sessions (id) ON DELETE CASCADE,
    teacher_id   BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(15) NOT NULL,            -- DUNG_GIO | VAO_TRE | VANG
    check_in_at  TIMESTAMPTZ,
    check_out_at TIMESTAMPTZ,
    note         VARCHAR(255),                    -- ghi chu khi admin cham tay
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT uq_session_teacher UNIQUE (session_id)
);

CREATE INDEX idx_sta_teacher ON session_teacher_attendance (teacher_id);
CREATE INDEX idx_sta_session ON session_teacher_attendance (session_id);
