-- =====================================================================
-- V28: Module TIN NHAN (message) + mo rong THONG BAO (notification)
--   messages: noi dung DAY DU (hop thu in-app). 1 su kien -> 1 message + 1 notification tro ve.
--   notifications: them read_at (da doc) + message_id (lien ket tin nhan day du).
-- Xem SPEC_ThongBao_TinNhan.md.
-- =====================================================================

CREATE TABLE messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    sender_user_id    BIGINT       REFERENCES users (id),        -- NULL = he thong
    type              VARCHAR(30)  NOT NULL,
    title             VARCHAR(200) NOT NULL,
    content           TEXT         NOT NULL,                     -- noi dung day du
    payload           TEXT,                                      -- JSON deep-link dang chuoi
    read_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100)
);
CREATE INDEX idx_messages_recipient ON messages (recipient_user_id, read_at, id DESC);

ALTER TABLE notifications ADD COLUMN read_at    TIMESTAMPTZ;
ALTER TABLE notifications ADD COLUMN message_id BIGINT REFERENCES messages (id);
CREATE INDEX idx_notifications_recipient ON notifications (recipient_user_id, read_at, id DESC);
