-- =====================================================================
-- V2: Module Bai Tap (Exercise)
-- Bao gom: exercises, choice_options, true_false_items + quyen EXERCISE
-- =====================================================================

CREATE TABLE exercises (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(50)  NOT NULL UNIQUE,
    title               VARCHAR(255) NOT NULL,
    grade_level         VARCHAR(50)  NOT NULL,
    subject             VARCHAR(100) NOT NULL,
    type                VARCHAR(30)  NOT NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    question_text       TEXT,
    question_image      VARCHAR(500),
    essay_answer        TEXT,
    essay_answer_image  VARCHAR(500),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100)
);

CREATE TABLE choice_options (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id BIGINT  NOT NULL REFERENCES exercises (id) ON DELETE CASCADE,
    sort_order  INT     NOT NULL DEFAULT 0,
    text        TEXT,
    image       VARCHAR(500),
    is_correct  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE true_false_items (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id BIGINT  NOT NULL REFERENCES exercises (id) ON DELETE CASCADE,
    sort_order  INT     NOT NULL DEFAULT 0,
    text        TEXT,
    image       VARCHAR(500),
    answer      BOOLEAN NOT NULL DEFAULT TRUE
);

-- Indexes cho cac truong loc / sap xep
CREATE INDEX idx_exercises_status     ON exercises (status);
CREATE INDEX idx_exercises_created_at ON exercises (created_at);
CREATE INDEX idx_exercises_grade      ON exercises (grade_level);
CREATE INDEX idx_exercises_subject    ON exercises (subject);
CREATE INDEX idx_choice_exercise      ON choice_options (exercise_id);
CREATE INDEX idx_tfi_exercise         ON true_false_items (exercise_id);

-- Dam bao trac nghiem chi co duy nhat 1 dap an dung tai DB layer
CREATE UNIQUE INDEX idx_choice_single_correct
    ON choice_options (exercise_id)
    WHERE is_correct = TRUE;

-- ---------------------------------------------------------------------
-- Quyen module Exercise
-- ---------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('EXERCISE:READ',   'EXERCISE', 'READ',   'Xem bai tap'),
    ('EXERCISE:WRITE',  'EXERCISE', 'WRITE',  'Tao / sua bai tap'),
    ('EXERCISE:DELETE', 'EXERCISE', 'DELETE', 'Xoa bai tap');

-- ADMIN: toan bo quyen EXERCISE (READ, WRITE, DELETE)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ADMIN'
  AND p.resource = 'EXERCISE';

-- TEACHER: doc + tao/sua bai tap (EXERCISE:READ + EXERCISE:WRITE)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'TEACHER'
  AND p.resource = 'EXERCISE'
  AND p.action IN ('READ', 'WRITE');

-- EMPLOYEE: chi xem bai tap (EXERCISE:READ only)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE'
  AND p.resource = 'EXERCISE'
  AND p.action = 'READ';
