-- =====================================================================
-- V31: Nhan xet bao cao (report_comments) + quyen REPORT:READ / REPORT:COMMENT
--   REPORT:READ    : ADMIN, EMPLOYEE, TEACHER, ASSISTANT, STUDENT, PARENT (scope o SecurityService)
--   REPORT:COMMENT : ADMIN, TEACHER, ASSISTANT, PARENT
-- Nhan xet neo theo (hoc vien, khoa hoc); tuy chon theo bai (exam_student_id).
-- visible_to_student = FALSE mac dinh (hoc sinh khong doc); GV co the bat cho tung nhan xet.
-- =====================================================================
CREATE TABLE report_comments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    class_id           BIGINT       NOT NULL REFERENCES classes (id) ON DELETE CASCADE,
    exam_student_id    BIGINT       REFERENCES exam_student (id) ON DELETE SET NULL,
    author_id          BIGINT       NOT NULL REFERENCES users (id),
    author_role        VARCHAR(20)  NOT NULL,
    content            VARCHAR(2000) NOT NULL,
    visible_to_student BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ,
    created_by         VARCHAR(100),
    updated_by         VARCHAR(100)
);
CREATE INDEX idx_report_comments_student_class ON report_comments (student_id, class_id);
CREATE INDEX idx_report_comments_exam_student  ON report_comments (exam_student_id);

-- -------------------------------------------------------------------
-- Quyen REPORT:READ / REPORT:COMMENT
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('REPORT:READ',    'REPORT', 'READ',    'Xem bao cao hoc tap'),
    ('REPORT:COMMENT', 'REPORT', 'COMMENT', 'Them nhan xet bao cao');

-- REPORT:READ cho TAT CA vai tro (scope du lieu do SecurityService kiem soat)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE p.code = 'REPORT:READ';

-- REPORT:COMMENT cho ADMIN, TEACHER, ASSISTANT, PARENT
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE p.code = 'REPORT:COMMENT'
  AND r.name IN ('ADMIN', 'TEACHER', 'ASSISTANT', 'PARENT');
