-- =====================================================================
-- V30: Module BAI VIET (post) + THONG BAO DO ADMIN SOAN (announcement)
--   posts: bai viet content hien tren Home mobile (noi dung MARKDOWN)
--   announcements: lich su thong bao admin soan (fan-out qua notify())
-- Xem SPEC_Home_BaiViet_ThongBaoAdmin.md.
-- =====================================================================

CREATE TABLE posts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200) NOT NULL,
    summary         VARCHAR(500),
    cover_image_url VARCHAR(500),
    content_md      TEXT         NOT NULL,
    status          VARCHAR(12)  NOT NULL DEFAULT 'DRAFT',   -- DRAFT | PUBLISHED | ARCHIVED
    pinned          BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100)
);
CREATE INDEX idx_posts_feed ON posts (status, pinned DESC, published_at DESC);

CREATE TABLE announcements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(200) NOT NULL,
    content_md     TEXT         NOT NULL,
    audience       VARCHAR(20)  NOT NULL,                    -- ALL | ROLE | CLASS | USERS
    audience_ref   VARCHAR(500),                             -- ROLE: csv role; CLASS: classId; USERS: csv userIds
    sent_count     INT          NOT NULL DEFAULT 0,
    post_id        BIGINT       REFERENCES posts (id),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100)
);
CREATE INDEX idx_announcements_created ON announcements (id DESC);

-- -------------------------------------------------------------------
-- Quyen POST:* / ANNOUNCE:*
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('POST:READ',      'POST',     'READ',  'Xem bai viet (quan tri)'),
    ('POST:WRITE',     'POST',     'WRITE', 'Tao / sua / dang bai viet'),
    ('ANNOUNCE:READ',  'ANNOUNCE', 'READ',  'Xem lich su thong bao da soan'),
    ('ANNOUNCE:WRITE', 'ANNOUNCE', 'WRITE', 'Soan / gui thong bao');

-- ADMIN + EMPLOYEE: toan quyen POST + ANNOUNCE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name IN ('ADMIN', 'EMPLOYEE') AND p.resource IN ('POST', 'ANNOUNCE');
