-- =====================================================================
-- V33: Thanh toan hoc phi
-- 1) Gia/buoi tren khoa hoc + tung buoi
-- 2) Giam gia theo hoc vien
-- 3) Cau hinh tai khoan nhan tien
-- 4) Dot thu hoc phi (invoice) + snapshot tung buoi
-- 5) Permission FEE:READ / FEE:WRITE
-- =====================================================================

ALTER TABLE classes ADD COLUMN price_per_session NUMERIC(12,0) NOT NULL DEFAULT 0;

ALTER TABLE class_sessions ADD COLUMN price NUMERIC(12,0) NOT NULL DEFAULT 0;
ALTER TABLE class_sessions ADD COLUMN price_overridden BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE class_students ADD COLUMN discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0;

CREATE TABLE payment_settings (
    id             BIGINT PRIMARY KEY,              -- luon = 1 (1 dong duy nhat)
    bank_bin       VARCHAR(10)  NOT NULL,           -- ma BIN NAPAS, vd 970436 (VCB)
    bank_name      VARCHAR(100) NOT NULL,           -- ten hien thi, vd 'Vietcombank'
    account_number VARCHAR(30)  NOT NULL,
    account_name   VARCHAR(100) NOT NULL,           -- ten chu TK (in hoa khong dau)
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);

CREATE TABLE tuition_invoices (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT NOT NULL REFERENCES users (id)   ON DELETE RESTRICT,
    class_id         BIGINT NOT NULL REFERENCES classes (id) ON DELETE RESTRICT,
    period_from      DATE NOT NULL,
    period_to        DATE NOT NULL,
    session_count    INT  NOT NULL,                 -- so buoi tinh phi
    gross_amount     NUMERIC(12,0) NOT NULL,        -- tong truoc giam
    discount_percent NUMERIC(5,2)  NOT NULL DEFAULT 0,  -- snapshot luc tao
    amount           NUMERIC(12,0) NOT NULL,        -- so tien phai thu (admin sua tay duoc khi DRAFT)
    payment_code     VARCHAR(40) NOT NULL UNIQUE,   -- '{username}-{4 ky tu}' — ma doi chieu CK
    status           VARCHAR(15) NOT NULL,          -- DRAFT | CONFIRMED | PAID | CANCELLED
    confirmed_at     TIMESTAMPTZ,
    paid_at          TIMESTAMPTZ,
    note             VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);
CREATE INDEX idx_ti_student ON tuition_invoices (student_id);
CREATE INDEX idx_ti_class_period ON tuition_invoices (class_id, period_from, period_to);
CREATE INDEX idx_ti_status ON tuition_invoices (status);
-- chong tao trung dot thu cho cung HV + lop + ky (tru don da huy)
CREATE UNIQUE INDEX uq_ti_student_class_period
    ON tuition_invoices (student_id, class_id, period_from, period_to)
    WHERE status <> 'CANCELLED';

CREATE TABLE tuition_invoice_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id   BIGINT NOT NULL REFERENCES tuition_invoices (id) ON DELETE CASCADE,
    session_id   BIGINT NOT NULL REFERENCES class_sessions (id)  ON DELETE RESTRICT,
    session_date DATE NOT NULL,                    -- snapshot
    price        NUMERIC(12,0) NOT NULL,           -- snapshot gia buoi luc chot
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100),
    CONSTRAINT uq_tii_invoice_session UNIQUE (invoice_id, session_id)
);

-- -------------------------------------------------------------------
-- Quyen FEE:READ / FEE:WRITE (copy pattern V24__init_leave.sql)
--   FEE:READ  -> ADMIN, EMPLOYEE
--   FEE:WRITE -> ADMIN, EMPLOYEE
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('FEE:READ',  'FEE', 'READ',  'Xem hoc phi'),
    ('FEE:WRITE', 'FEE', 'WRITE', 'Quan ly hoc phi (tao/xac nhan/thu)');

-- ADMIN: READ + WRITE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN' AND p.resource = 'FEE';

-- EMPLOYEE: READ + WRITE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE' AND p.resource = 'FEE' AND p.action IN ('READ', 'WRITE');
