-- =====================================================================
-- V34: Xu hoc vien (tien ao)
-- 1) coin_wallets  : so du hien tai (1 dong/HV, lazy-create)
-- 2) coin_transactions : ledger moi lan cong/tru + snapshot balance_after
-- 3) Permission COIN:READ (ADMIN, EMPLOYEE) / COIN:WRITE (ADMIN)
-- =====================================================================
CREATE TABLE coin_wallets (
    user_id    BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    balance    BIGINT NOT NULL DEFAULT 0 CHECK (balance >= 0),
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);

CREATE TABLE coin_transactions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    amount        BIGINT NOT NULL,              -- duong = cong, am = tru, <> 0
    balance_after BIGINT NOT NULL,              -- snapshot so du sau giao dich (doi soat)
    reason        VARCHAR(255) NOT NULL,        -- ly do admin nhap
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)   -- created_by = admin thao tac
);
CREATE INDEX idx_ct_user ON coin_transactions (user_id, created_at DESC);

-- -------------------------------------------------------------------
-- Quyen COIN:READ / COIN:WRITE (copy pattern V24__init_leave.sql)
--   COIN:READ  -> ADMIN, EMPLOYEE
--   COIN:WRITE -> ADMIN
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('COIN:READ',  'COIN', 'READ',  'Xem Xu hoc vien'),
    ('COIN:WRITE', 'COIN', 'WRITE', 'Cong/tru Xu hoc vien');

-- ADMIN: READ + WRITE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN' AND p.resource = 'COIN';

-- EMPLOYEE: READ
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE' AND p.resource = 'COIN' AND p.action = 'READ';
