-- =====================================================================
-- V35: Giao bai luyen tap (practice_assignments) — SPEC_BaoCao §10
-- PH (hoac GV) giao de luyen tap cho con/HV tu man chi tiet bai thi.
-- De luyen = de SUPPLEMENTARY sinh tu kho, gan dung 1 chuyen de.
-- Quyen REPORT:ASSIGN: PARENT, ADMIN, TEACHER, ASSISTANT (G5).
-- =====================================================================
CREATE TABLE practice_assignments (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id        BIGINT      NOT NULL UNIQUE REFERENCES exams (id) ON DELETE CASCADE,
    source_exam_id BIGINT      REFERENCES exams (id) ON DELETE SET NULL,
    student_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    parent_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    class_id       BIGINT      NOT NULL REFERENCES classes (id) ON DELETE CASCADE,
    status         VARCHAR(15) NOT NULL DEFAULT 'ASSIGNED',   -- ASSIGNED | SUBMITTED
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100)
);
CREATE INDEX idx_practice_student_class ON practice_assignments (student_id, class_id);
CREATE INDEX idx_practice_parent ON practice_assignments (parent_id);

INSERT INTO permissions (code, resource, action, description)
VALUES ('REPORT:ASSIGN', 'REPORT', 'ASSIGN', 'Giao bai luyen tap cho con/HV');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE p.code = 'REPORT:ASSIGN'
  AND r.name IN ('PARENT', 'ADMIN', 'TEACHER', 'ASSISTANT');
