-- =====================================================================
-- V38: Kho video bai giang (YouTube, dung lai nhieu buoi) + gan vao buoi hoc
-- Xem SPEC_VideoBaiGiang_Zoom.md §2, §3.5
-- =====================================================================
CREATE TABLE lecture_videos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    youtube_url      VARCHAR(500) NOT NULL UNIQUE,
    description      TEXT,
    topic_id         BIGINT REFERENCES topics (id) ON DELETE SET NULL,
    thumbnail_url    VARCHAR(500),
    duration_seconds INT,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100)
);
CREATE INDEX idx_lecture_videos_topic ON lecture_videos (topic_id);

CREATE TABLE session_videos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES class_sessions (id) ON DELETE CASCADE,
    video_id   BIGINT NOT NULL REFERENCES lecture_videos (id) ON DELETE RESTRICT,
    sort_order INT    NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_session_video UNIQUE (session_id, video_id)
);
CREATE INDEX idx_session_videos_session ON session_videos (session_id);
CREATE INDEX idx_session_videos_video ON session_videos (video_id);

-- -------------------------------------------------------------------
-- Quyen SESSION_CONTENT:READ / SESSION_CONTENT:WRITE
-- Khong tai dung CLASS:WRITE vi EMPLOYEE (chi CLASS:READ) cung phai nhap
-- duoc video/zoom, ma khong duoc phep sua gio/phong/huy buoi. Xem
-- SPEC_VideoBaiGiang_Zoom.md §1 quyet dinh #4.
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('SESSION_CONTENT:READ',  'SESSION_CONTENT', 'READ',  'Xem video/zoom cua buoi hoc'),
    ('SESSION_CONTENT:WRITE', 'SESSION_CONTENT', 'WRITE', 'Nhap video/zoom cho buoi hoc');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name IN ('ADMIN', 'EMPLOYEE', 'TEACHER') AND p.resource = 'SESSION_CONTENT';
