-- =====================================================================
-- V39: Link Zoom cua buoi hoc (1:N) + mac dinh cho quy tac lich
-- Xem SPEC_VideoBaiGiang_Zoom.md §2, §3.3
-- =====================================================================
CREATE TABLE session_zoom_links (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT       NOT NULL REFERENCES class_sessions (id) ON DELETE CASCADE,
    label      VARCHAR(100) NOT NULL DEFAULT 'Link chinh',
    zoom_url   VARCHAR(500) NOT NULL,
    meeting_id VARCHAR(50),
    passcode   VARCHAR(50),
    sort_order INT          NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
CREATE INDEX idx_session_zoom_links_session ON session_zoom_links (session_id);

ALTER TABLE class_schedules ADD COLUMN default_zoom_url VARCHAR(500);
