-- =====================================================================
-- V3: Module Files (luu metadata file upload)
-- =====================================================================

CREATE TABLE files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(100) NOT NULL,
    relative_path VARCHAR(300) NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    checksum      VARCHAR(64),
    folder        VARCHAR(50),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100)
);

CREATE INDEX idx_files_status   ON files (status);
CREATE INDEX idx_files_checksum ON files (checksum);
CREATE INDEX idx_files_folder   ON files (folder);

-- ---------------------------------------------------------------------
-- Quyen module Files
-- ---------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('FILE:READ',   'FILE', 'READ',   'Xem / liet ke file'),
    ('FILE:WRITE',  'FILE', 'WRITE',  'Tai len file'),
    ('FILE:DELETE', 'FILE', 'DELETE', 'Xoa file');

-- ADMIN: full
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN' AND p.resource = 'FILE';

-- TEACHER: READ + WRITE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'TEACHER' AND p.resource = 'FILE' AND p.action IN ('READ','WRITE');

-- EMPLOYEE: READ
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE' AND p.resource = 'FILE' AND p.action = 'READ';
