-- =====================================================================
-- V41: Khoi MARKETING Trang chu mobile (banner khuyen mai, danh muc theo
-- khoi lop kem gia/GV/giam gia, trust bar, testimonial).
-- Day la NOI DUNG QUANG CAO rieng, KHONG lien quan classes/class_sessions
-- that (hoc vien da ghi danh) — chi hien thi tren Trang chu de gioi thieu.
-- Xem ThietKe/Mobile/files/m-home.html cho thiet ke goc.
-- =====================================================================

CREATE TABLE marketing_categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(100) NOT NULL,
    emoji           VARCHAR(8),
    banner_tag      VARCHAR(30)  NOT NULL,
    banner_headline VARCHAR(150) NOT NULL,
    gradient_start  VARCHAR(9)   NOT NULL,
    gradient_end    VARCHAR(9)   NOT NULL,
    accent_color    VARCHAR(9)   NOT NULL,
    display_order   INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100)
);
CREATE INDEX idx_marketing_categories_order ON marketing_categories (display_order);

CREATE TABLE promoted_courses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT       NOT NULL REFERENCES marketing_categories (id) ON DELETE CASCADE,
    title           VARCHAR(150) NOT NULL,
    teacher_name    VARCHAR(100) NOT NULL,
    price           BIGINT       NOT NULL,
    old_price       BIGINT,
    badge           VARCHAR(10)  NOT NULL DEFAULT 'NONE',   -- NONE | HOT | NEW
    gradient_start  VARCHAR(9)   NOT NULL,
    gradient_end    VARCHAR(9)   NOT NULL,
    icon_key        VARCHAR(30)  NOT NULL DEFAULT 'school',
    display_order   INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100)
);
CREATE INDEX idx_promoted_courses_category ON promoted_courses (category_id, display_order);

CREATE TABLE testimonials (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    meta           VARCHAR(150) NOT NULL,
    quote          VARCHAR(500) NOT NULL,
    display_order  INT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100)
);
CREATE INDEX idx_testimonials_order ON testimonials (display_order);

-- Chi 1 dong duy nhat (id = 1) — chi so tin cay hien o Trang chu.
CREATE TABLE trust_stats (
    id       BIGINT PRIMARY KEY,
    years    VARCHAR(20) NOT NULL,
    students VARCHAR(20) NOT NULL,
    teachers VARCHAR(20) NOT NULL,
    CONSTRAINT trust_stats_singleton CHECK (id = 1)
);

-- -------------------------------------------------------------------
-- Quyen MARKETING:* — de danh cho Admin panel sua noi dung sau nay.
-- Man doc /api/v1/home/marketing KHONG can quyen nay (chi @isAuthenticated,
-- giong pattern PostController.feed()) — quyen o day chi cho admin WRITE.
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('MARKETING:READ',  'MARKETING', 'READ',  'Xem noi dung marketing Trang chu (quan tri)'),
    ('MARKETING:WRITE', 'MARKETING', 'WRITE', 'Sua danh muc/khoa quang cao/testimonial Trang chu');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name IN ('ADMIN', 'EMPLOYEE') AND p.resource = 'MARKETING';

-- -------------------------------------------------------------------
-- Seed du lieu mau (khop dung mock da dung o Mobile) — production co the
-- xoa/sua qua Admin panel sau nay khi co UI quan tri.
-- -------------------------------------------------------------------
INSERT INTO marketing_categories
    (id, title, emoji, banner_tag, banner_headline, gradient_start, gradient_end, accent_color, display_order, created_at)
VALUES
    (1, 'Luyện thi vào 10', '🔥', 'KHỐI 9', 'Chinh phục kỳ thi vào 10', '#C7261C', '#FF5D6C', '#FF5D6C', 0, now()),
    (2, 'Khối THCS (6–9)', NULL, 'THCS', 'Nền tảng vững — điểm cao', '#1E2FB8', '#2E43E8', '#2E43E8', 1, now()),
    (3, 'Khối THPT (10–12)', NULL, 'THPT', 'Bứt phá điểm thi', '#0F6B45', '#2FAE7A', '#2FAE7A', 2, now());

INSERT INTO promoted_courses
    (category_id, title, teacher_name, price, old_price, badge, gradient_start, gradient_end, icon_key, display_order, created_at)
VALUES
    (1, 'Toán 9 — Luyện thi vào 10', 'GV Nguyễn Mạnh Cường', 2850000, 3560000, 'HOT', '#2E43E8', '#5B6CFF', 'percent', 0, now()),
    (1, 'Tiếng Anh 9 — Luyện thi vào 10', 'GV Hoàng Hải Yến', 2750000, 3200000, 'NEW', '#2FAE7A', '#5FCB9F', 'translate', 1, now()),
    (1, 'Vật lý 9 — Luyện thi vào 10', 'GV Vũ Khắc Ngọc', 2500000, NULL, 'NONE', '#FF5D6C', '#FF8A93', 'hub', 2, now()),

    (2, 'Toán 8 — Học chủ động', 'GV Nguyễn Quốc Sơn', 2100000, NULL, 'NONE', '#2E43E8', '#5B6CFF', 'percent', 0, now()),
    (2, 'Ngữ văn 7 — Học chủ động', 'GV Nguyễn Phi Hùng', 1980000, NULL, 'NONE', '#C97F1B', '#F5C877', 'book', 1, now()),
    (2, 'Hóa học 9 — Nền tảng', 'GV Ánh Dương', 2250000, 2700000, 'NEW', '#2FAE7A', '#5FCB9F', 'science', 2, now()),

    (3, 'Sinh học 12 — Nền tảng', 'GV Ánh Dương', 2550000, 3100000, 'HOT', '#2FAE7A', '#5FCB9F', 'eco', 0, now()),
    (3, 'Vật lý 11 — Ôn tập & Kiểm tra', 'GV Vũ Khắc Ngọc', 2400000, NULL, 'NONE', '#2E43E8', '#5B6CFF', 'hub', 1, now()),
    (3, 'Tiếng Anh 12 — Nền tảng', 'GV Nguyễn Trung Nguyên', 2650000, NULL, 'NONE', '#FF5D6C', '#FF8A93', 'translate', 2, now());

INSERT INTO testimonials (name, meta, quote, display_order, created_at) VALUES
    ('Chị Hoàng Lan', 'PH lớp Toán 9', 'Con cải thiện điểm Toán rõ rệt sau 2 tháng học tại DECA.', 0, now()),
    ('Minh Quân', 'HS lớp Lý 10', 'Bài kiểm tra nhanh giúp em ôn lại kiến thức ngay sau buổi học.', 1, now());

INSERT INTO trust_stats (id, years, students, teachers) VALUES (1, '8 năm', '1.200+', '35 GV');

-- Dong bo sequence IDENTITY cho marketing_categories sau khi insert id tuong minh (1,2,3).
SELECT setval(pg_get_serial_sequence('marketing_categories', 'id'), 3, true);
