-- =====================================================================
-- V46: Nap Xu bang chuyen khoan (VietQR, ty le co dinh 1.000 VND = 1 Xu).
-- HOC SINH tao yeu cau (PENDING) -> ADMIN doi soat ngan hang thu cong roi
-- confirm de cong Xu (dung lai COIN:READ/COIN:WRITE da co san tu V?? coin).
-- =====================================================================

CREATE TABLE coin_topup_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    amount_vnd     NUMERIC(12,0) NOT NULL,
    coin_amount    BIGINT NOT NULL,
    payment_code   VARCHAR(40) NOT NULL UNIQUE,
    status         VARCHAR(15) NOT NULL,          -- PENDING | CONFIRMED | CANCELLED
    confirmed_at   TIMESTAMPTZ,
    note           VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);
CREATE INDEX idx_ctr_student ON coin_topup_requests (student_id);
CREATE INDEX idx_ctr_status ON coin_topup_requests (status);
