-- =====================================================================
-- V47: Nhap bai tap/de thi theo lo (tu file du lieu AI boc tach tu Word).
-- Mo rong trang thai Exercise/Exam them PENDING/DELETED (enum Java da sua,
-- cot status van la VARCHAR thuong, khong co CHECK constraint nen khong can
-- doi gi o day) + bang theo doi lo nhap + cot lien ket tren exercises/exams.
-- =====================================================================

CREATE TABLE import_batches (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_name  VARCHAR(255) NOT NULL,
    subject_id        BIGINT NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    topic_id          BIGINT REFERENCES topics (id) ON DELETE SET NULL,
    exam_name         VARCHAR(255),
    exam_id           BIGINT REFERENCES exams (id) ON DELETE SET NULL,
    total_count       INT NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS', -- IN_PROGRESS | COMPLETED | ABANDONED
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);
CREATE INDEX idx_import_batches_created_by ON import_batches (created_by);
CREATE INDEX idx_import_batches_status ON import_batches (status);

ALTER TABLE exercises ADD COLUMN import_batch_id BIGINT REFERENCES import_batches (id) ON DELETE SET NULL;
ALTER TABLE exercises ADD COLUMN order_index INT;
CREATE INDEX idx_exercises_import_batch ON exercises (import_batch_id);

ALTER TABLE exams ADD COLUMN import_batch_id BIGINT REFERENCES import_batches (id) ON DELETE SET NULL;
CREATE INDEX idx_exams_import_batch ON exams (import_batch_id);
