-- =====================================================================
-- V4: Bang luu sequence sinh ma bai tap / de thi
-- =====================================================================

CREATE TABLE code_sequences (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code VARCHAR(2)  NOT NULL,   -- TO, LY, HO, AN, SI, SU, DI, VA, TI
    grade_code   VARCHAR(2)  NOT NULL,   -- 01 - 12
    year_offset  INT         NOT NULL,   -- nam_tao - 2026 (0, 1, 2, ...)
    last_seq     BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_code_seq UNIQUE (subject_code, grade_code, year_offset)
);
