-- =====================================================================
-- V50: Khoa hoc marketing — noi dung hien thi + dang ky tu phuc vu +
-- cau hinh hotline dung chung. Xem docs/DecaMath/.scratch/course-page-design-plan.html
-- =====================================================================

-- 1) Gia tron goi cho dang ky tu phuc vu (rieng biet price_per_session/coin_price).
--    NULL = khoa nay chua mo dang ky kieu nay (an nut Dang ky + QR o Card/trang chi tiet).
ALTER TABLE classes ADD COLUMN full_price NUMERIC(12,0);

-- 2) Noi dung hien thi khoa hoc (title/anh/bai gioi thieu) — 1-1 voi classes.
CREATE TABLE class_marketing_content (
    class_id         BIGINT PRIMARY KEY REFERENCES classes (id) ON DELETE CASCADE,
    title            VARCHAR(200),
    cover_image_url  VARCHAR(500),
    content_md       TEXT,
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);

-- 3) Yeu cau dang ky khoa hoc (truoc khi ghi danh) — doi chieu chuyen khoan thu cong.
CREATE TABLE class_enrollment_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id          BIGINT NOT NULL REFERENCES classes (id) ON DELETE RESTRICT,
    student_id        BIGINT NOT NULL REFERENCES users (id)   ON DELETE RESTRICT,
    amount            NUMERIC(12,0) NOT NULL,
    registration_code VARCHAR(40)  NOT NULL UNIQUE,
    status            VARCHAR(15)  NOT NULL, -- PENDING | CONFIRMED | CANCELLED
    confirmed_at      TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);
CREATE INDEX idx_cer_class ON class_enrollment_requests (class_id);
CREATE INDEX idx_cer_student ON class_enrollment_requests (student_id);
CREATE INDEX idx_cer_status ON class_enrollment_requests (status);
-- chong tao trung yeu cau dang cho xu ly cho cung 1 hoc vien + khoa
CREATE UNIQUE INDEX uq_cer_student_class_pending
    ON class_enrollment_requests (student_id, class_id)
    WHERE status = 'PENDING';

-- 4) Cau hinh dung chung toan he thong (hotline...) — single-row, id = 1.
CREATE TABLE app_settings (
    id              BIGINT PRIMARY KEY,
    support_hotline VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ,
    created_by VARCHAR(100), updated_by VARCHAR(100)
);
INSERT INTO app_settings (id, support_hotline, created_at, updated_at)
VALUES (1, '1900 9999', now(), now());
