-- =====================================================================
-- V6: Danh muc mon hoc (catalog co dinh, chi doc)
-- Seed 49 ban ghi: 7 mon x 7 khoi (6-12)
-- =====================================================================

CREATE TABLE subjects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    grade_level VARCHAR(50)  NOT NULL,
    CONSTRAINT uq_subjects_name_grade UNIQUE (name, grade_level)
);

CREATE INDEX idx_subjects_grade ON subjects (grade_level);

-- -------------------------------------------------------------------
-- Seed: 7 mon x 7 khoi = 49 ban ghi
-- Ma: L{mon}{khoi}T  vi du LTO06T = Toan Khoi 6
-- -------------------------------------------------------------------
INSERT INTO subjects (code, name, grade_level) VALUES
('LTO06T', 'Toán',       'Khối 6'),  ('LTO07T', 'Toán',       'Khối 7'),
('LTO08T', 'Toán',       'Khối 8'),  ('LTO09T', 'Toán',       'Khối 9'),
('LTO10T', 'Toán',       'Khối 10'), ('LTO11T', 'Toán',       'Khối 11'),
('LTO12T', 'Toán',       'Khối 12'),

('LLY06T', 'Vật lý',    'Khối 6'),  ('LLY07T', 'Vật lý',    'Khối 7'),
('LLY08T', 'Vật lý',    'Khối 8'),  ('LLY09T', 'Vật lý',    'Khối 9'),
('LLY10T', 'Vật lý',    'Khối 10'), ('LLY11T', 'Vật lý',    'Khối 11'),
('LLY12T', 'Vật lý',    'Khối 12'),

('LHO06T', 'Hóa học',   'Khối 6'),  ('LHO07T', 'Hóa học',   'Khối 7'),
('LHO08T', 'Hóa học',   'Khối 8'),  ('LHO09T', 'Hóa học',   'Khối 9'),
('LHO10T', 'Hóa học',   'Khối 10'), ('LHO11T', 'Hóa học',   'Khối 11'),
('LHO12T', 'Hóa học',   'Khối 12'),

('LVA06T', 'Ngữ văn',   'Khối 6'),  ('LVA07T', 'Ngữ văn',   'Khối 7'),
('LVA08T', 'Ngữ văn',   'Khối 8'),  ('LVA09T', 'Ngữ văn',   'Khối 9'),
('LVA10T', 'Ngữ văn',   'Khối 10'), ('LVA11T', 'Ngữ văn',   'Khối 11'),
('LVA12T', 'Ngữ văn',   'Khối 12'),

('LAN06T', 'Tiếng Anh', 'Khối 6'),  ('LAN07T', 'Tiếng Anh', 'Khối 7'),
('LAN08T', 'Tiếng Anh', 'Khối 8'),  ('LAN09T', 'Tiếng Anh', 'Khối 9'),
('LAN10T', 'Tiếng Anh', 'Khối 10'), ('LAN11T', 'Tiếng Anh', 'Khối 11'),
('LAN12T', 'Tiếng Anh', 'Khối 12'),

('LSI06T', 'Sinh học',  'Khối 6'),  ('LSI07T', 'Sinh học',  'Khối 7'),
('LSI08T', 'Sinh học',  'Khối 8'),  ('LSI09T', 'Sinh học',  'Khối 9'),
('LSI10T', 'Sinh học',  'Khối 10'), ('LSI11T', 'Sinh học',  'Khối 11'),
('LSI12T', 'Sinh học',  'Khối 12'),

('LTI06T', 'Tin học',   'Khối 6'),  ('LTI07T', 'Tin học',   'Khối 7'),
('LTI08T', 'Tin học',   'Khối 8'),  ('LTI09T', 'Tin học',   'Khối 9'),
('LTI10T', 'Tin học',   'Khối 10'), ('LTI11T', 'Tin học',   'Khối 11'),
('LTI12T', 'Tin học',   'Khối 12');

-- -------------------------------------------------------------------
-- Quyen module Subject: chi READ (danh muc co dinh, khong can WRITE/DELETE)
-- Tat ca role deu duoc xem de dung lam dropdown
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('SUBJECT:READ', 'SUBJECT', 'READ', 'Xem mon hoc');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE p.code = 'SUBJECT:READ';
