-- =====================================================================
-- V8: Module Lop thuc te (classes)
-- 1 lop thuoc 1 mon hoc; 1 mon co nhieu lop (1:N)
-- =====================================================================

CREATE TABLE classes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(50)  NOT NULL,
    subject_id  BIGINT       NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    start_date  DATE,
    end_date    DATE,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ,
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100)
);

CREATE INDEX idx_classes_subject_id ON classes (subject_id);
CREATE INDEX idx_classes_status     ON classes (status);
CREATE INDEX idx_classes_created_at ON classes (created_at);

-- -------------------------------------------------------------------
-- Quyen module Class
-- -------------------------------------------------------------------
INSERT INTO permissions (code, resource, action, description) VALUES
    ('CLASS:READ',   'CLASS', 'READ',   'Xem lop'),
    ('CLASS:WRITE',  'CLASS', 'WRITE',  'Tao / sua lop'),
    ('CLASS:DELETE', 'CLASS', 'DELETE', 'Xoa lop');

-- ADMIN: toan bo
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ADMIN'
  AND p.resource = 'CLASS';

-- TEACHER: doc + tao/sua
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'TEACHER'
  AND p.resource = 'CLASS'
  AND p.action IN ('READ', 'WRITE');

-- EMPLOYEE: chi xem
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE'
  AND p.resource = 'CLASS'
  AND p.action = 'READ';
